### ISSUE TITLE
Applicative / Monad laws for SplineT

### ISSUE THREAD

**Issue by schell** [schell/varying#11]
Sometime before a 1.0 release it would be great to get in the proofs of the applicative/monad laws for `SplineT`.

**Comment by mitchellwrosen** [comment]
@schell Following up on this, I realized the manual proofs actually aren't necessary for `SplineT`, because `SplineT a b m c ~ VarT (ExceptT c m) a b`, which we know is a monad. Yay!

Edit: Er, nevermind... `VarT` isn't a monad

**Comment by schell** [comment]
Oh no! Thought we had an easy win there for a moment.
