### ISSUE TITLE
AMP simplifications

### ISSUE THREAD

**Issue by ggreif** [schell/varying#21]
Since travis only tests GHC v7.10 and up, every `Monad` is automatically an `Applicative`. A lot of signatures could be simplified.

Setting a suitable `base` version (to `base-4.8.0.0`) will ensure this.

It'll probably eliminate a bunch of warnings on modern GHCs.

Would you accept a pull request to this effect?

**Comment by schell** [comment]
I definitely would! Thank you for your help :)

**Comment by ggreif** [comment]
Thanks!
