### ISSUE TITLE
Broken ArrowLoop Instance

### ISSUE THREAD

**Issue by RiugaBachi** [schell/varying#32]
A `rec` block inside VarT will cause an infinite cyclic reference crash, even for simple cases where the variable is fed constant input and is not referenced outside `rec`. Tested over both IO and Identity. Below is a minimal complete example. Compiler is GHC 8.6.5 using base 4.12.0.0.

```hs
module Main where

import Control.Varying.Core
import Control.Varying.Event
import Control.Arrow
import Data.Functor.Identity

main :: IO ()
main = do
  testVarOver testVar [5.0]
  where
    testVar :: VarT IO Double (Maybe Double)
    testVar = proc val -> do
      rec _ <- returnA -< 0.5
      returnA -< Just 5.0

```

For reference, the equivalent of the above runs fine in `wires`.

**Comment by schell** [comment]
Thanks for the report @RiugaBachi, I'll see how it was implemented in `wires`.

**Comment by schell** [comment]
Pattern matching inside 'loop' was a bit too strict, is all. I should have a new version up on hackage soonish. Thanks!
