### ISSUE TITLE
How would I create my own event source?

### ISSUE THREAD

**Issue by kozross** [schell/varying#39]
Background on this: I want to create a program which watches a directory, responding to different things happening in it. I'm using [``fsnotify``][1] for this, but I am unsure how I would create a ``VarT`` for such a thing. How would I create a 'source of events' that I can then work with using this library?

[1]: http://hackage.haskell.org/package/fsnotify-0.3.0.1

**Comment by schell** [comment]
I've forgotten the details of `fsnotify` so forgive me there, but `VarT` is meant to be pulled from a main loop. You could have `fsnotify` write events into an `IORef [Event]` (however it gets events) and then fold your root `VarT` over all of those. Here's some hand-wavey haskell:

```haskell
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Control.Concurrent.Async
import Data.Bifunctor (first)

data MyProgramType = ...

rootVar :: VarT m Event MyProgramType
rootVar = ... 

main :: IO () 
main = do 
  eventsRef <- newIORef [] 
  _ <- async $ fsnotifyDoTheThingToPutEventsInto eventsRef
  let 
    loop var = do 
      (outputs :: [MyProgramType], nextVar) <- 
        readIORef eventsRef >>= scanVar var
      traverse_ doSomethingLikeRender ouputs 
      loop nextVar
  loop rootVar
```

**Comment by kozross** [comment]
OK, it seems I have some idea how to do this now - thanks for getting back to me. Gonna close this.
